"""empty message

Revision ID: 194209ef6928
Revises: 
Create Date: 2022-04-10 20:46:44.769674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194209ef6928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquilino')
    # ### end Alembic commands ###
