"""empty message

Revision ID: 290e874f0c72
Revises: 194209ef6928
Create Date: 2022-04-10 20:51:54.025071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290e874f0c72'
down_revision = '194209ef6928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquilino', sa.Column('nome', sa.String(), nullable=True))
    op.add_column('inquilino', sa.Column('data_nascimento', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquilino', 'data_nascimento')
    op.drop_column('inquilino', 'nome')
    # ### end Alembic commands ###
